⬢[anasko@toolbox NotebookAPI]$ pylint NotebookAPI.py
************* Module NotebookAPI
NotebookAPI.py:15:0: C0301: Line too long (309/100) (line-too-long)
NotebookAPI.py:15:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:20:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:21:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:22:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:32:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:33:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:34:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:35:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:36:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:38:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:41:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:42:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:42:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
NotebookAPI.py:43:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:44:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:45:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:48:0: C0301: Line too long (109/100) (line-too-long)
NotebookAPI.py:48:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:51:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:52:0: C0301: Line too long (112/100) (line-too-long)
NotebookAPI.py:52:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:54:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:55:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:56:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:57:0: C0301: Line too long (108/100) (line-too-long)
NotebookAPI.py:57:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:64:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:65:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:66:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:67:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:70:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:71:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:72:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:73:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:74:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:81:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:82:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:83:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:84:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:85:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:87:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:88:0: C0301: Line too long (109/100) (line-too-long)
NotebookAPI.py:88:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:91:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:92:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:93:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:94:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:96:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:97:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:98:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:108:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:109:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:110:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:111:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:113:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:114:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:115:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:116:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:119:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:120:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:121:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:122:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:123:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:125:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:126:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:129:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:130:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:132:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:133:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:134:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:135:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:142:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:143:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:144:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:145:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:147:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:148:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:149:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:150:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:153:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:156:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:157:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:158:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:160:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:161:0: W0311: Bad indentation. Found 3 spaces, expected 12 (bad-indentation)
NotebookAPI.py:163:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:164:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:165:0: C0301: Line too long (121/100) (line-too-long)
NotebookAPI.py:165:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:175:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:176:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:177:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:178:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:180:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:181:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:182:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:183:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:186:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:187:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:188:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:189:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:190:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:193:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:194:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:195:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:196:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:197:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:198:0: C0301: Line too long (183/100) (line-too-long)
NotebookAPI.py:198:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:205:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:206:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:207:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:208:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:210:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:211:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:212:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:213:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:216:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:217:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:218:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:219:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:220:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:221:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:224:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:225:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:226:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:227:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:229:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:230:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:231:0: C0301: Line too long (164/100) (line-too-long)
NotebookAPI.py:231:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:240:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:247:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:248:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:250:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:253:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:254:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:257:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:259:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:261:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:262:0: W0311: Bad indentation. Found 3 spaces, expected 12 (bad-indentation)
NotebookAPI.py:263:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:264:0: W0311: Bad indentation. Found 3 spaces, expected 12 (bad-indentation)
NotebookAPI.py:266:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:268:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:275:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:276:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:277:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:278:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:281:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:282:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:283:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:284:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:291:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:292:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:293:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:294:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:297:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:298:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:299:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:300:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
NotebookAPI.py:302:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:309:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
NotebookAPI.py:1:0: C0103: Module name "NotebookAPI" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:1:0: C0114: Missing module docstring (missing-module-docstring)
NotebookAPI.py:1:0: E0401: Unable to import 'flask' (import-error)
NotebookAPI.py:2:0: E0401: Unable to import 'peewee' (import-error)
NotebookAPI.py:2:0: W0401: Wildcard import peewee (wildcard-import)
NotebookAPI.py:3:0: W0401: Wildcard import dbclasses (wildcard-import)
NotebookAPI.py:9:0: E0401: Unable to import 'werkzeug.utils' (import-error)
NotebookAPI.py:14:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:19:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:30:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:35:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:35:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:56:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:56:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:35:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:62:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:66:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:66:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:73:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:73:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:66:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:79:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:84:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:84:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:97:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:97:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:84:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:106:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:110:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:110:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:115:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:115:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:122:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:122:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:134:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:134:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:110:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:140:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:144:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:144:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:149:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:149:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:164:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:164:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:144:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:173:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:177:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:177:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:182:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:182:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:189:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:189:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:197:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:197:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:177:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:203:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:207:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:207:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:212:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:212:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:220:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:220:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:230:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:230:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:207:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:239:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:245:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:263:9: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:263:2: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:263:2: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:273:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:277:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:277:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:283:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:283:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:277:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:289:0: C0116: Missing function or method docstring (missing-function-docstring)
NotebookAPI.py:293:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:293:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:299:8: W0703: Catching too general exception Exception (broad-except)
NotebookAPI.py:299:1: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
NotebookAPI.py:293:1: W0612: Unused variable 'e' (unused-variable)
NotebookAPI.py:4:0: C0411: standard import "import datetime" should be placed before "from flask import Flask, jsonify, request, make_response, send_from_directory" (wrong-import-order)
NotebookAPI.py:5:0: C0411: standard import "import base64" should be placed before "from flask import Flask, jsonify, request, make_response, send_from_directory" (wrong-import-order)
NotebookAPI.py:7:0: C0411: standard import "import os" should be placed before "from flask import Flask, jsonify, request, make_response, send_from_directory" (wrong-import-order)
NotebookAPI.py:9:0: C0411: third party import "from werkzeug.utils import secure_filename" should be placed before "from dbclasses import *" (wrong-import-order)

------------------------------------
Your code has been rated at -4.72/10
